steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build', 
            '--tag=gcr.io/$PROJECT_ID/openmatch-evaluator:dev',
            '-f', 'Dockerfile.evaluator', 
            '.'
        ]
images: ['gcr.io/$PROJECT_ID/openmatch-evaluator:dev']

