steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/openmatch-mmf:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build', 
            '--tag=gcr.io/$PROJECT_ID/openmatch-mmf:$TAG_NAME', 
            '--cache-from', 'gcr.io/$PROJECT_ID/openmatch-mmf:latest',
            '.'
        ]
images: ['gcr.io/$PROJECT_ID/openmatch-mmf:$TAG_NAME']
